# Generated by Django 5.2.6 on 2025-09-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_catagory_remove_event_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.catagory'),
        ),
    ]
