# Generated by Django 5.2.6 on 2025-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_event_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participated_event',
            field=models.ManyToManyField(related_name='participents', to='task.event'),
        ),
    ]
