# Generated by Django 5.2.6 on 2025-09-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_participant_participated_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catagorys', to='task.catagory'),
        ),
    ]
